- name: Install git
  yum:
    name: git
    state: latest

- name: Check if puppet repo installed
  command: ls /etc/yum.repos.d/puppetlabs-pc1.repo
  register: puppetlabsrepo
  ignore_errors: yes

- name: Install puppet repo
  command: /usr/bin/yum -y install https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
  when: puppetlabsrepo|failed

- name: Install puppet client
  yum:
    name: puppet-agent
    state: latest

- name: Install puppet server
  yum:
    name: puppetserver
    state: latest
  notify: Puppet Server Run

- name: Enable Puppet
  service:
    name: puppetserver
    enabled: yes

- name: Set up cron to pull from git
  cron:
    name: "Get puppet code"
    minute: "*/10"
    job: "cd /etc; git clone https://github.com/stevshil/puppettrain.git >>/var/log/messages 2>&1"

- name: Check if /etc/puppetlabs/code is a symlink to /etc/puppetlabs/puppettrain/code
  stat:
    path: /etc/puppetlabs/code
  register: codedir

- name: Remove code directory if not symlink
  file:
    path: /etc/puppetlabs/code
    state: absent
  when: codedir.stat.islnk == False

- name: Create symlink to code
  file:
    src: /etc/puppetlabs/puppettrain/code
    dest: /etc/puppetlabs/code
    state: link
  when: codedir.stat.islnk == False
