---
- name: Add Jenkins user
  user:
    name: jenkins
    comment: jenkins user
    home: /var/lib/jenkins
    state: present

- name: Check if jenkins repo installed
  command: ls /etc/yum.repos.d/jenkins.repo
  register: jenkinsrepo
  ignore_errors: yes

- name: Download Jenkins repo config
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d
    mode: 0644
    owner: root
    group: root
  when: jenkinsrepo|failed
  register: dorepo

- name: Install Jenkins repo trust
  command: /bin/rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
  when: jenkinsrepo|failed

- name: Install Java
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: Jenkins service
  copy:
    src: "{{ role_path }}/files/jenkins-sysd"
    dest: /usr/lib/systemd/system/jenkins.service
    owner: root
    group: root
    mode: 0755

- name: Enable jenkins in systemd
  file:
    src: /usr/lib/systemd/system/
    dest: /etc/systemd/system/multi-user.target.wants/jenkins.service
    state: link

- name: Ensure systemd is up to date
  command: systemctl daemon-reload

- name: Check if config already in place
  command: ls /var/lib/jenkins/.jenkins/plugins
  ignore_errors: true
  register: configbase

- name: Copy base config
  copy:
    #src: "{{ role_path }}/files/jenkinsbase.tgz"
    src: "{{ role_path }}/files/jenkins-essentials.tgz"
    dest: /tmp/jenkinsbase.tgz
  when: configbase|failed

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest

- name: Start Jenkins preconfig
  service:
    name: jenkins
    state: started

- name: Stop Jenkins preconfig
  service:
    name: jenkins
    state: stopped

- name: Check if archive is on server from previous failure
  command: /bin/ls /tmp/jenkinsbase.tgz
  register: chkbase
  ignore_errors: yes

- name: Extract base config
  command: /bin/tar xvf /tmp/jenkinsbase.tgz -C /var/lib/jenkins/.jenkins
  when: chkbase|succeeded
  register: extractbase

- name: Set jenkins user as owner of directory /var/lib/jenkins
  file:
    owner: jenkins
    path: /var/lib/jenkins
    recurse: yes

- name: Remove the jenkins base archive
  file:
    path: /tmp/jenkinsbase.tgz
    state: absent
  when: extractbase|succeeded

- name: Enable Jenkins
  service:
    name: jenkins
    enabled: yes

- name: Final start Jenkins
  service:
    name: jenkins
    state: started
