- name: Enable RPMfusion
  package:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ os_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ os_version }}.noarch.rpm"
    state: present

- name: Enable Docker CE
  shell: "dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: Enable Skype
  shell: "dnf config-manager --add-repo https://repo.skype.com/rpm/stable/skype-stable.repo"

- name: Enable Brave
  yum_repository:
    name: brave
    description: brave browser
    baseurl: https://brave-browser-rpm-release.s3.brave.com/$basearch/
    gpgcheck: yes
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: Enable Slack
  yum_repository:
    name: slack
    description: Slack
    baseurl: "https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64"
    gpgcheck: yes
    gpgkey: https://packagecloud.io/gpg.key
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Enable VirtualBox
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc

- name: Enable TPS
  yum_repository:
    name: TPS
    description: TPS Services Ltd
    baseurl: http://192.168.10.54/rpms
    enabled: yes
    gpgcheck: no

- name: Enable Azure
  yum_repository:
    name: azure-cli
    description: Azure CLI
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Enable Atom
  yum_repository:
    name: Atom
    description: Atom Editor
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/$basearch
    gpgcheck: yes
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey

- name: Google Chrome
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
